[package]
name = "week9"
version = "0.1.0"
authors = ["Sajjad Taheri <sajjadt@uci.edu>"]

[dependencies]
regex="1"
may = "0.3"
itertools = "0.7"

[[bin]]
name = "map_reduce"
path = "src/map_reduce.rs"
